#!/usr/bin/env ruby

require "compare_files"

options = CompareFiles::Cli.parse!

puts CompareFiles.new_left(options.left, options.right)

if options.remember
  IO.write(options.remember, CompareFiles::Cli.standardize_input(options.left).join("\n"))
end

